AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  StyleGuideCopsOnly: false

Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/TrailingBlankLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true

Performance/UnfreezeString:
  Enabled: true
