sudo: false
cache: bundler
language: ruby
rvm:
  - 2.4.2
install: bundle install --path=vendor/bundle --retry=3 --jobs=3
before_install: gem install bundler
after_success: bundle exec rake benchmarks

env:
  matrix:
  - "RAILS_VERSION=4.2"
  - "RAILS_VERSION=5.0"
  - "RAILS_VERSION=5.1"
