sudo: false
cache: bundler
language: ruby
rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head

env:
  global:
    - GIT_NAME: Travis CI
    - GIT_EMAIL: nobody@nobody.org

  matrix:
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=5.2.0"
  - "RAILS_VERSION=6.0.0"

install: bundle install --path=vendor/bundle --retry=3

before_install:
  - gem install bundler
  - nvm install 9

after_success:
  - npm install docpress && $(npm bin)/docpress build
  - if [ -n "$TRAVIS_TAG" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm install git-update-ghpages && $(npm bin)/git-update-ghpages yosiat/panko_serializer _docpress; fi
  - bundle exec rake benchmarks

matrix:
  exclude:
    - rvm: 2.7.0
      env: RAILS_VERSION=4.2.0
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
